### ISSUE TITLE
Tries to replace '__proto__' and 'constructor'

### ISSUE THREAD

**Issue by axchow** [tfausak/atom-conceal#1]
Conceal is greedy with the 'Object' properties, `__proto__` and `constructor`. A quick fix is something like:

```coffeescript
replacement = replacements[element.textContent]
continue unless replacement and (typeof replacement is 'string')
```

**Comment by tfausak** [comment]
I don't use this package anymore. I use [Fira Code](https://github.com/tonsky/FiraCode) instead. If you are interested in fixing this, I accept pull requests :smile:

**Comment by axchow** [comment]
Yep, ligatures are a better way to support this as of Atom 1.1. I'm using Monoid myself.
Thanks for your work on it all the same.
