### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by nielsAD** [tfausak/atom-conceal#4]
I noticed you tagged a new release version (`0.0.2`), but `package.json` and https://atom.io/packages/conceal both refer to version `0.0.1`, is this on purpose?

**Comment by tfausak** [comment]
It's not on purpose. I forgot to update the `package.json`. I'll release a new version. Sorry!

**Comment by tfausak** [comment]
Should be fixed by https://github.com/tfausak/atom-conceal/commit/91970274f40571c373b0066adb7db31c9d72578d and https://github.com/tfausak/atom-conceal/releases/tag/v0.0.3.

**Comment by nielsAD** [comment]
Sorry to be bothering you again with this :sweat_smile:, but the [Atom package repository](https://atom.io/packages/conceal) still says version `0.0.1`. I think you have to use `apm publish` to actually update the version in the package manager.

**Comment by tfausak** [comment]
Dang, I really dropped the ball on this one. Conceal version 0.0.3 has actually been published this time.

![screen shot 2016-03-31 at 9 52 42 am](https://cloud.githubusercontent.com/assets/408753/14179874/5f8fb3d0-f726-11e5-814a-4611a1e7874d.png)
