### ISSUE TITLE
Deprecated selector in `conceal/styles/conceal.less`

### ISSUE THREAD

**Issue by mikelsr** [tfausak/atom-conceal#9]
In `conceal/styles/conceal.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed::before` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed::before`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="1"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="1"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="2"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="2"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="3"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="3"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="4"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="4"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="5"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="5"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="6"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="6"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="7"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="7"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="8"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="8"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="9"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="9"]`

* `atom-text-editor::shadow .line:not(.cursor-line) .concealed[data-replacement-length="10"]` => `atom-text-editor.editor .line:not(.cursor-line) .syntax--concealed[data-replacement-length="10"]`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by tfausak** [comment]
I think this may have already been fixed by #7. Can you verify?

**Comment by mikelsr** [comment]
That's right! Sorry for not seeing it, my last update was to `v0.0.4` and `apm` said no more updates were available.

**Comment by tfausak** [comment]
No problem. Thanks for reporting!
